=== EbonyLouis/incubation-verifiable-credential-selector/banking_vc_schemas/vc_transactions.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://api.sophtron.com/schema/draft/vc/bankaccounts.json",
  "title": "Banking VC - BankAccounts",
  "description": "List of accounts schema of banking verifiable credentials",
  "type": "object",
  "properties": {
    "id": {
      "description": "",
      "type": "string"
    },
    "name": {
      "description": "Name of the subject",
      "type": "string"
    },
    "fiAttributes": {
      "$ref": "common.json#/definitions/FinancialInstitution"
    },
    "accounts": {
      "type": "array",
      "items":{
        "$ref": "common.json#/definitions/BankAccount"
      }
    }
  },
  "additionalProperties": false,
  "minProperties": 4
}

=== EbonyLouis/incubation-verifiable-credential-selector/banking_vc_schemas/examples/vc_transactions_subject.json
{
  "accounts": [
    {
      "accountNumber": "1234",
      "accountType": "Credit_Card",
      "accountname": "Credit Card",
      "availableBalnace": 0,
      "id": "https://api.sophtron.com/api/userInstituionAccount/48b339c7-2260-4aac-894f-23153e1d2e9b",
      "routingNumber": null,
      "status": "active",
      "transactions": [
        {
          "amount": 0,
          "accountId": "https://api.sophtron.com/api/userInstituionAccount/48b339c7-2260-4aac-894f-23153e1d2e9b",
          "category": "Bank fee",
          "transactionTimestamp": "2022-04-15T00:00:00",
          "postedTimestamp": "2022-04-15T00:00:00",
          "description": "Sophtron Fee",
          "payee": "merchant",
          "status": "posted",
          "transactionId": "https://api.sophtron.com/api/userInstituionAccount/8781abd5-9b40-4fd7-8430-a975d0276314",
          "transactionType": "Debit"
        }
      ],
      "updatedDate": "2022-04-15T12:15:15.68"
    }
  ],
  "id": "http://api.sophtron.com/api/userinstitution/0044c82b-f8a9-4508-921a-e49bff69a705",
  "fiAttributes": {
    "name": "Sophtron Bank",
    "logo_url": "https://sophtron.com/Images/logo.png"
  },
  "name": "John Example"
}
